### ISSUE TITLE
Question for the content of the imbalance experiment Makefile's meaning

### ISSUE THREAD

**Issue by zli19** [rsspp/experiments#3]
Hello,
I have noticed that you revised your Makefile with an optimized structure.
Can you further explain what these methods mean? How these methods related to the RSS++ fastclick's source code?(I can not find vendor/nicscheduler in fastclick-dumpaccel, on which the imbalance experiment set up.) Are they hardcoded in the dpdk.testie?

```
METHODS=rsspp+rss:RSS rsspp+sprayer:Sprayer "rsspp+pipeline,queue:Software Shared Queue" "rsspp+pipeline,rr:Software RR Queue" "rsspp+pipeline,flowrr:Software Stateful RR" "rsspp+pipeline,flowrr,AWARE=1:Software Stateful Load"
METHODS+="rsspp+staticmetron:Metron Static" "rsspp+dynamicmetron:Metron Dynamic"
METHODS+="rsspp+pianorss:RSSPP"
```

Thanks.

**Comment by tbarbette** [comment]
Instead of copy pasting every methods everywhere I used a common variable. Then in practice I would in general test only some methods together, that is why it is split in multiple lines, easy to comment out.

Then each chunk of the methods follows the npf format "repository+tags,overridenvariable=value:Pretty name". Mostly tags are used to enable different piece of codes in the testie file to use RSS, or Metron, or ..., or RSS++. Then NPF will run the test for each methods.
That commit is just refactoring.

Now I tried to build a demo VM with that test, but I can't because virtual drivers do not support RSS... SRIOV does but if the demo requires a real NIC it kind of defeats.the purpose...

**Comment by zli19** [comment]
Thank you for your patience in explaining these simple things for me... In fact, my whole goal is to try to reproduce the experimental data and generate graphs on my server... I used to generate the data in the old version, but the plotted graph seems unchanged no matter how I change the parameters in the dpdk.testie file... I appreciate your plan and your effort, but the existing project already seems too huge and complex for me to reproduce successfully...

**Comment by tbarbette** [comment]
Well I'd say if you have one you have the others... ;) You're not far from it.
